/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: node scripts/starter-checks.js content-manifest
 *
 * This file provides statically bundled content manifest data.
 * No runtime fs dependency - works in dev and production builds.
 */

import type { Locale } from '@/types/content.types';

export interface ContentEntry {
  type: "pages";
  locale: Locale;
  slug: string;
  extension: string;
  filePath: string;
  relativePath: string;
  source: "active-content";
  metadata: Record<string, unknown>;
  content: string;
}

export interface ContentManifest {
  entries: ContentEntry[];
  byKey: Record<string, ContentEntry>;
}

const _entries: ContentEntry[] = [
  {
    "type": "pages",
    "locale": "en",
    "slug": "about",
    "extension": ".mdx",
    "filePath": "/content/pages/en/about.mdx",
    "relativePath": "content/pages/en/about.mdx",
    "source": "active-content",
    "metadata": {
      "locale": "en",
      "title": "About This Reference Site",
      "description": "A neutral reference page for the business identity, operating model and proof a future B2B inquiry site should provide.",
      "slug": "about",
      "publishedAt": "2026-08-06",
      "updatedAt": "2026-08-06",
      "author": "B2B Inquiry Site Base",
      "layout": "default",
      "showToc": true,
      "lastReviewed": "2026-08-06",
      "draft": false,
      "seo": {
        "title": "About This B2B Inquiry Reference Site",
        "description": "Reference content showing where a future business should explain its identity, operating model and buyer proof."
      }
    },
    "content": "\nThis is **reference content for a reusable B2B inquiry site**, not a description of a real company. Replace it with owner-confirmed facts before any production deployment.\n\n## State who the buyer is dealing with\n\nName the legal entity, trading name, location and role in the supply chain. Keep the website, quotation, invoice and payment beneficiary consistent.\n\n## Explain how the business works\n\nDescribe what the company makes, supplies or coordinates. Make the boundary between in-house work, partner work and buyer responsibility easy to verify.\n\n## Show useful proof\n\nUse evidence a buyer can check: approved specifications, samples, inspection options, project records, certifications or written service commitments. Do not publish claims that the owner cannot support.\n\n## Give the next step\n\nThe site should end with one clear path: **[start an inquiry](/request-quote)** with the details needed for a useful reply.\n"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "contact",
    "extension": ".mdx",
    "filePath": "/content/pages/en/contact.mdx",
    "relativePath": "content/pages/en/contact.mdx",
    "source": "active-content",
    "metadata": {
      "locale": "en",
      "title": "Contact",
      "description": "Reference contact content for a B2B inquiry site.",
      "slug": "contact",
      "publishedAt": "2026-08-06",
      "updatedAt": "2026-08-06",
      "author": "B2B Inquiry Site Base",
      "layout": "default",
      "showToc": false,
      "lastReviewed": "2026-08-06",
      "draft": false,
      "seo": {
        "title": "Contact — B2B Inquiry Site Reference",
        "description": "Reference contact page showing the minimum information a future business should replace."
      }
    },
    "content": "\nThis page is a **non-production reference**. Replace the identity, email, location, response time and operating hours with owner-confirmed details.\n\nThe fastest route is the **[inquiry form](/request-quote)**. A useful request normally includes the requirement, quantity or scope, destination market and timing.\n\n**Reference email:** sales@example.invalid\n\n**Reference business:** Northstar Industrial Reference\n\n**Reference location:** Replace with the real registered or operating location.\n"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "privacy",
    "extension": ".mdx",
    "filePath": "/content/pages/en/privacy.mdx",
    "relativePath": "content/pages/en/privacy.mdx",
    "source": "active-content",
    "metadata": {
      "locale": "en",
      "title": "Privacy Policy Reference",
      "description": "Non-production reference text for documenting how a B2B inquiry site handles submitted information.",
      "slug": "privacy",
      "publishedAt": "2026-08-06",
      "updatedAt": "2026-08-06",
      "author": "B2B Inquiry Site Base",
      "layout": "legal",
      "showToc": true,
      "lastReviewed": "2026-08-06",
      "draft": false,
      "seo": {
        "title": "Privacy Policy Reference",
        "description": "Non-production reference text that must be reviewed and replaced for the operating business and jurisdiction."
      }
    },
    "content": "\n> Reference only. This is not legal advice or a production privacy policy. The operating business must replace and review it for its actual tools, data flows and jurisdictions.\n\n## Site operator\n\nIdentify the legal entity operating the website, its contact details and any representative required by the applicable jurisdiction.\n\n## Information collected\n\nDescribe the fields submitted through the inquiry form and any technical, security, analytics or campaign data the deployed site actually collects.\n\n## Purpose and sharing\n\nExplain why the business uses inquiry data, which service providers receive it and whether it is used for sales follow-up, quotation, fulfilment or measurement.\n\n## Retention and requests\n\nState the real retention policy and provide a working contact method for access, correction or deletion requests.\n\n## Cookies and analytics\n\nList only the storage and integrations enabled in the deployed environment. Keep consent behaviour consistent with the site's actual configuration.\n"
  },
  {
    "type": "pages",
    "locale": "en",
    "slug": "terms",
    "extension": ".mdx",
    "filePath": "/content/pages/en/terms.mdx",
    "relativePath": "content/pages/en/terms.mdx",
    "source": "active-content",
    "metadata": {
      "locale": "en",
      "title": "Website Terms Reference",
      "description": "Non-production reference text for the website-use and inquiry-stage boundaries of a B2B site.",
      "slug": "terms",
      "publishedAt": "2026-08-06",
      "updatedAt": "2026-08-06",
      "author": "B2B Inquiry Site Base",
      "layout": "legal",
      "showToc": true,
      "lastReviewed": "2026-08-06",
      "draft": false,
      "seo": {
        "title": "Website Terms Reference",
        "description": "Non-production reference text that must be reviewed and replaced for the operating business and offer."
      }
    },
    "content": "\n> Reference only. This is not legal advice or a production terms document. Replace it with terms reviewed for the real business, offer and jurisdiction.\n\n## Site operator\n\nIdentify the legal entity responsible for the website and provide a working contact method.\n\n## Website information\n\nExplain whether pages, downloads and examples are general information, specifications, quotations or contractual commitments. Do not imply guarantees the business has not approved.\n\n## Inquiries and quotations\n\nState that an inquiry does not create an order. Define which written document confirms price, scope, timing, delivery, payment and any custom requirements.\n\n## Buyer and supplier responsibilities\n\nDescribe the real boundary for selection, installation, compliance, operation, maintenance and local approvals where those issues apply.\n\n## Updates\n\nState how updated website terms take effect and which signed commercial documents take priority for an actual transaction.\n"
  }
];

const _byKeyIndex: Record<string, number> = {
  "pages/en/about": 0,
  "pages/en/contact": 1,
  "pages/en/privacy": 2,
  "pages/en/terms": 3
};

const _byKey: Record<string, ContentEntry> = Object.fromEntries(
  Object.entries(_byKeyIndex).map(([key, idx]) => [key, _entries[idx]!]),
);

export const CONTENT_MANIFEST: ContentManifest = {
  entries: _entries,
  byKey: _byKey,
} as const;
